# Generated by Django 5.1.6 on 2025-05-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_subject_alter_chapter_slug_alter_topic_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_name',
            field=models.CharField(max_length=100),
        ),
    ]
