# Generated by Django 5.1.6 on 2025-08-12 07:23

import django.db.models.deletion
import django.utils.timezone
import submission.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0007_alter_chapter_chapter_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSubmission',
            fields=[
                ('submission_uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(default='Exam-Level', max_length=20)),
                ('multiple_choice', models.BooleanField(default=False)),
                ('submitter_display_name', models.CharField(blank=True, max_length=120)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_submissions', to='contents.chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_submissions', to='contents.subject')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_submissions', to='contents.topic')),
            ],
            options={
                'db_table': 'question_submission_inbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_order', models.PositiveIntegerField()),
                ('content_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image')], max_length=15)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image_content', models.ImageField(blank=True, null=True, upload_to=submission.models.submission_media_path)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='submission.questionsubmission')),
            ],
            options={
                'db_table': 'question_submission_order',
                'ordering': ['section_order'],
            },
        ),
    ]
