# Generated by Django 5.1.6 on 2025-08-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsubmission',
            name='submitter_display_name',
        ),
        migrations.RemoveField(
            model_name='questionsubmission',
            name='submitter_email',
        ),
    ]
