# Generated by Django 5.1.6 on 2025-08-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_remove_questionsubmission_submitter_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsubmission',
            name='multiple_choice',
        ),
    ]
