# Generated by Django 5.1.6 on 2025-08-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_remove_questionsubmission_multiple_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsubmission',
            name='difficulty',
        ),
        migrations.DeleteModel(
            name='SubmissionOrder',
        ),
    ]
