# Generated by Django 5.1.6 on 2026-02-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialaccess',
            name='problems_viewed',
        ),
        migrations.AddField(
            model_name='trialaccess',
            name='problems_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
