# Generated by Django 5.1.6 on 2025-08-09 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_alter_chapter_chapter_name'),
        ('problems', '0003_seenquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='seenquestion',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='seenquestion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='seenquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='seenquestion',
            constraint=models.UniqueConstraint(fields=('user', 'question', 'topic'), name='uq_seen_user_question_topic'),
        ),
    ]
