# Generated by Django 5.1.6 on 2025-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_rename_timestamp_seenquestion_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
