name: Build and deploy Python app to Azure Web App - chuba-app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Optional: early failure check (you can delete this block later if you want faster CI)
      - name: Create venv, install deps (optional preflight)
        run: |
          python -m venv .venv
          source .venv/bin/activate
          cd vce
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Upload the *contents* of vce/ so artifact root == backend root
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            vce/**
            !vce/.venv/
            !.venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chuba-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6BD7AF0680EB4DEDB7E24B007852B7B6 }}
          package: .
